# Generated by Django 4.0.6 on 2022-08-01 15:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=26, null=True)),
                ('lname', models.CharField(blank=True, max_length=26, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=26, null=True)),
                ('contact', models.CharField(blank=True, max_length=26, null=True)),
                ('position', models.CharField(blank=True, max_length=26, null=True)),
                ('pin', models.CharField(blank=True, max_length=26, null=True)),
                ('username', models.CharField(max_length=26)),
                ('password', models.CharField(max_length=26)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('checkin', 'checkin'), ('checkout', 'checkout')], default='checkin', max_length=10)),
                ('time', models.DateTimeField(default=datetime.datetime(2022, 8, 1, 15, 16, 19, 889181, tzinfo=utc))),
                ('message', models.TextField(blank=True, max_length=1000, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
